language: r
cache:
   directories:
      - $HOME/.R/oysteR/cache/
   packages: true
r:
  - oldrel
  - release
  - devel

after_success: >
   test $TRAVIS_PULL_REQUEST == "false" &&
   test $TRAVIS_BRANCH == "master" &&
   Rscript -e 'covr::codecov()'
